//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.empServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeDTO", Namespace="http://schemas.datacontract.org/2004/07/EMS.Models")]
    [System.SerializableAttribute()]
    public partial class EmployeeDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmployeeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SalaryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeId {
            get {
                return this.EmployeeIdField;
            }
            set {
                if ((this.EmployeeIdField.Equals(value) != true)) {
                    this.EmployeeIdField = value;
                    this.RaisePropertyChanged("EmployeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Salary {
            get {
                return this.SalaryField;
            }
            set {
                if ((this.SalaryField.Equals(value) != true)) {
                    this.SalaryField = value;
                    this.RaisePropertyChanged("Salary");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="empServiceRef.IEmployeeService")]
    public interface IEmployeeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/getEmployee", ReplyAction="http://tempuri.org/IEmployeeService/getEmployeeResponse")]
        Client.empServiceRef.EmployeeDTO getEmployee(string emp_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/getEmployee", ReplyAction="http://tempuri.org/IEmployeeService/getEmployeeResponse")]
        System.Threading.Tasks.Task<Client.empServiceRef.EmployeeDTO> getEmployeeAsync(string emp_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/getEmployees", ReplyAction="http://tempuri.org/IEmployeeService/getEmployeesResponse")]
        Client.empServiceRef.EmployeeDTO[] getEmployees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/getEmployees", ReplyAction="http://tempuri.org/IEmployeeService/getEmployeesResponse")]
        System.Threading.Tasks.Task<Client.empServiceRef.EmployeeDTO[]> getEmployeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/getEmployeesByDepartmentName", ReplyAction="http://tempuri.org/IEmployeeService/getEmployeesByDepartmentNameResponse")]
        Client.empServiceRef.EmployeeDTO[] getEmployeesByDepartmentName(string dept_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/getEmployeesByDepartmentName", ReplyAction="http://tempuri.org/IEmployeeService/getEmployeesByDepartmentNameResponse")]
        System.Threading.Tasks.Task<Client.empServiceRef.EmployeeDTO[]> getEmployeesByDepartmentNameAsync(string dept_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/addEmployee", ReplyAction="http://tempuri.org/IEmployeeService/addEmployeeResponse")]
        string addEmployee(Client.empServiceRef.EmployeeDTO dto, string deptName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/addEmployee", ReplyAction="http://tempuri.org/IEmployeeService/addEmployeeResponse")]
        System.Threading.Tasks.Task<string> addEmployeeAsync(Client.empServiceRef.EmployeeDTO dto, string deptName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/updateEmployee", ReplyAction="http://tempuri.org/IEmployeeService/updateEmployeeResponse")]
        string updateEmployee(string emp_name, Client.empServiceRef.EmployeeDTO e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/updateEmployee", ReplyAction="http://tempuri.org/IEmployeeService/updateEmployeeResponse")]
        System.Threading.Tasks.Task<string> updateEmployeeAsync(string emp_name, Client.empServiceRef.EmployeeDTO e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/deleteEmployee", ReplyAction="http://tempuri.org/IEmployeeService/deleteEmployeeResponse")]
        string deleteEmployee(string emp_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/deleteEmployee", ReplyAction="http://tempuri.org/IEmployeeService/deleteEmployeeResponse")]
        System.Threading.Tasks.Task<string> deleteEmployeeAsync(string emp_name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeeServiceChannel : Client.empServiceRef.IEmployeeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeServiceClient : System.ServiceModel.ClientBase<Client.empServiceRef.IEmployeeService>, Client.empServiceRef.IEmployeeService {
        
        public EmployeeServiceClient() {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client.empServiceRef.EmployeeDTO getEmployee(string emp_name) {
            return base.Channel.getEmployee(emp_name);
        }
        
        public System.Threading.Tasks.Task<Client.empServiceRef.EmployeeDTO> getEmployeeAsync(string emp_name) {
            return base.Channel.getEmployeeAsync(emp_name);
        }
        
        public Client.empServiceRef.EmployeeDTO[] getEmployees() {
            return base.Channel.getEmployees();
        }
        
        public System.Threading.Tasks.Task<Client.empServiceRef.EmployeeDTO[]> getEmployeesAsync() {
            return base.Channel.getEmployeesAsync();
        }
        
        public Client.empServiceRef.EmployeeDTO[] getEmployeesByDepartmentName(string dept_name) {
            return base.Channel.getEmployeesByDepartmentName(dept_name);
        }
        
        public System.Threading.Tasks.Task<Client.empServiceRef.EmployeeDTO[]> getEmployeesByDepartmentNameAsync(string dept_name) {
            return base.Channel.getEmployeesByDepartmentNameAsync(dept_name);
        }
        
        public string addEmployee(Client.empServiceRef.EmployeeDTO dto, string deptName) {
            return base.Channel.addEmployee(dto, deptName);
        }
        
        public System.Threading.Tasks.Task<string> addEmployeeAsync(Client.empServiceRef.EmployeeDTO dto, string deptName) {
            return base.Channel.addEmployeeAsync(dto, deptName);
        }
        
        public string updateEmployee(string emp_name, Client.empServiceRef.EmployeeDTO e) {
            return base.Channel.updateEmployee(emp_name, e);
        }
        
        public System.Threading.Tasks.Task<string> updateEmployeeAsync(string emp_name, Client.empServiceRef.EmployeeDTO e) {
            return base.Channel.updateEmployeeAsync(emp_name, e);
        }
        
        public string deleteEmployee(string emp_name) {
            return base.Channel.deleteEmployee(emp_name);
        }
        
        public System.Threading.Tasks.Task<string> deleteEmployeeAsync(string emp_name) {
            return base.Channel.deleteEmployeeAsync(emp_name);
        }
    }
}
